logging:
    file:
        name: /logs/lotteOn.log

    level:
        jdbc:
            resultsettable: debug
            sqlonly: debug
            sqltiming: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        root: info
        org.springframework.web: DEBUG
server:
    port: 8085
    servlet:
        context-path: /

spring:
    application:
        name: LotteOnProject-3조
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        password: Qwe123~!
        url: jdbc:mysql://43.202.32.28:3306/lotteProject
        username: lotte
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    devtools:
        livereload:
            enabled: true
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
    web:
        resources:
            static-locations:
                - classpath:/static/
                - file:uploads/
    thymeleaf:
        cache: false
        check-template-location: true
        enabled: true
        prefix: classpath:/templates/
        suffix: .html